import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "@/theme/fonts"; // Import from your new fonts file
import ThemeRegistry from "@/theme/themeRegistry"; // Import the registry

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {/* <ThemeRegistry> */}
          {children}
        {/* </ThemeRegistry> */}
      </body>
    </html>
  );
}