import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "@/theme/fonts"; // Import from your new fonts file

export const metadata: Metadata = {
  title: "Honcho Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
          {children}
      </body>
    </html>
  );
}